defaults:
  - model: resnet34
  - dataset: cifar10

training:
  epochs: 50
  lr: 0.1
  momentum: 0.9
  weight_decay: 5e-4
  batch_size: 64
  num_workers: 4
  seed: 42
  device: cuda

logging:
  log_dir: ./runs/${now:%Y-%m-%d_%H-%M-%S}
  tensorboard: true
  use_notebook: false
